global:
  image:
    pullPolicy: Never

gateway:
  serviceType: NodePort

nats:
  container:
    image:
      pullPolicy: Always
  reloader:
    image:
      pullPolicy: Always
  config:
    jetstream:
      enabled: true
      fileStore:
        pvc:
          size: 256Mi
  natsBox:
    container:
      image:
        pullPolicy: Always
