apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-orders-service
  labels:
    app: orders-service
    app.kubernetes.io/part-of: roundtrip
spec:
  ports:
    - name: grpc
      port: {{ .Values.grpcPort }}
      targetPort: {{ .Values.grpcPort }}
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
  selector:
    app: orders-service
