apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-processing-service
  labels:
    app: processing-service
    app.kubernetes.io/part-of: roundtrip
spec:
  ports:
    - name: metrics
      port: {{ .Values.metricsPort }}
      targetPort: {{ .Values.metricsPort }}
  selector:
    app: processing-service
